name: Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim-version: [ "v0.9.0", "v0.9.1" ]

    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: MunifTanjim/setup-neovim-action@v1
        with:
          tag: ${{ matrix.neovim-version }}
      - name: Unit tests
        run: |
          just test
